### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dlangille**
correct typo

### CODE REVIEW

**Comment by johnko** [comment]
@dlangille Good to see you here.

I think this was just fixed, as long as @michaeldexter doesn't revert 2b155c59c0fb835ce6369a74681969faec4adbcc

**Comment by dlangille** [comment]
That bastard!  ;)

**Comment by johnko** [comment]
Also duplicate of #25

**Comment by dlangille** [comment]
*sigh* ;)

**Pull request merged**
